import Head from 'next/head';
import Profile from '../components/Profile';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Profile />
      <div className="flex gap-x-4 ml-5">
        <button className="bg-white ring-red-1 shadow-2xl focus:ring-2 rounded-lg p-5">
          Create to do{" "}
        </button>
        <button className="bg-white ring-red-1 focus:ring-2 rounded-lg p-5">
          help
        </button>
      </div>
    </div>
  );
}
